
Student.create!([
  {first_name: "Phil", last_name: "Pondo", email: "phil@gmail.com", password: "password", phone_number: "200-111-0101", bio: "There once was a cat in a hat", linkedin_url: "https://www.linkedin.com/in/phillippondo", twitter_handle: "@JurassicPark2go", website_url: "https://memebase.cheezburger.com/thisisphotobomb", resume_url: "http://hackertyper.com/", github_url: "https://www.github.com/philpondo", photo_url: "https://vignette.wikia.nocookie.net/yugioh/images/c/c0/ExodiatheForbiddenOne-TF04-JP-VG.jpg/revision/latest?cb=20120420185052"},
  {first_name: "Steven", last_name: "Chen", email: "steven@gmail.com", password: "password", phone_number: "002-131-9191", bio: "There once was a dog in a log", linkedin_url: "https://www.linkedin.com/in/steven-chen-735526fewd/", twitter_handle: "@elonmusk", website_url: "https://www.gutenberg.org/", resume_url: "http://beesbeesbees.com/", github_url: "https://www.github.com/stratos-chen", photo_url: "https://i.pinimg.com/originals/c8/ac/a9/c8aca99124c9b3f7d9b9435619861f60.jpg"},
  {first_name: "Luke", last_name: "Dietz", email: "luke@gmail.com", password: "password", phone_number: "401-555-4343", bio: "There once was a mouse in a house", linkedin_url: "www.linkedin.com/in/lukedietz", twitter_handle: "@kanyewest", website_url: "https://presidentialpickuplines.tumblr.com/", resume_url: "https://en.wikipedia.org/wiki/List_of_individual_dogs", github_url: "https://www.github.com/lddietz", photo_url: "https://i.pinimg.com/736x/f4/59/6d/f4596ddedeecc91d796084fa7a66246e.jpg"},
  {first_name: "Erik", last_name: "Alvar", email: "erik@gmail.com", password: "password", phone_number: "201-656-4343", bio: "There once was a raccoon in a cartoon", linkedin_url: "https://www.linkedin.com/in/erikalvar/", twitter_handle: "@god", website_url: "https://kimjongillookingatthings.tumblr.com/", resume_url: "https://sleepyti.me/", github_url: "https://www.github.com/erikalvar", photo_url: "https://media.comicbook.com/2020/07/digimon-adventure-brachimon-1227583.jpeg?auto=webp&width=1200&height=628&crop=1200:628,smart"},
  {first_name: "Carl", last_name: "Hauck", email: "carl@gmail.com", password: "password", phone_number: "001-155-4263", bio: "There once was a fish with a wish", linkedin_url: "https://www.linkedin.com/in/carlhauck/", twitter_handle: "@jack", website_url: "https://www.rrrather.com/", resume_url: "https://www.whatshouldireadnext.com/", github_url: "https://www.github.com/carlhauck", photo_url: "https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Instagram_egg.jpg/220px-Instagram_egg.jpg"},
  {first_name: "Hubert", last_name: "Shon", email: "hubert@gmail.com", password: "password", phone_number: "991-195-9349", bio: "There once was a dragon in a wagon", linkedin_url: "https://www.linkedin.com/in/hubert-shon/", twitter_handle: "@TheOnion", website_url: "https://www.cleverbot.com/", resume_url: "https://thisissand.com/", github_url: "https://www.github.com/hubertshon", photo_url: "https://dam.generac.com/ImConvServlet/imconv/e81c03905be5d3c946638e5e4521feb0d5b10a5d/440Wx440H?assetDescr=CE73016XEN_0"},
  {first_name: "Irving", last_name: "Villasenor", email: "irving@gmail.com", password: "password", phone_number: "891-185-9889", bio: "There once was a lizard in a wizard", linkedin_url: "https://www.linkedin.com/in/irving-villase%C3%B1or-5038071a9/", twitter_handle: "@neiltyson", website_url: "https://www.appropedia.org/Solar_Charged_Lawnmower", resume_url: "https://www.sporcle.com/", github_url: "https://www.github.com/irvingvillasenor", photo_url: "https://c.tadst.com/gfx/600x337/full-moon.png?1"},
  {first_name: "Iris", last_name: "Kuzmenko", email: "iris@gmail.com", password: "password", phone_number: "191-115-9877", bio: "There once was a snake in a rake", linkedin_url: "https://www.linkedin.com/in/iris-kuzmenko-b0504117b/", twitter_handle: "@Wikipedia", website_url: "https://www.theflatearthsociety.org/home/", resume_url: "https://www.poptropica.com/", github_url: "https://github.com/iris-kuzmenko", photo_url: "https://images2.persgroep.net/rcs/GKETsBQ1lpOKyuZx3YoMzM5hxRU/diocontent/161192301/_fitwidth/1240?appId=93a17a8fd81db0de025c8abd1cca1279&quality=0.9"},
  {first_name: "Rebecca", last_name: "Doukas", email: "rebecca@gmail.com", password: "password", phone_number: "081-005-9009", bio: "There once was a turtle in a girtle", linkedin_url: "https://www.linkedin.com/in/rebecca-doukas/", twitter_handle: "@RickandMorty", website_url: "https://badkidsjokes.tumblr.com/", resume_url: "http://www.foddy.net/2010/10/qwop/", github_url: "https://www.github.com/rdoukas", photo_url: "https://cdn.britannica.com/s:900x675/15/162615-131-0CBB2CBE/island-Caribbean.jpg"},
  {first_name: "James", last_name: "Odegaard", email: "james@gmail.com", password: "password", phone_number: "541-006-9609", bio: "There once was a lion named Ryan", linkedin_url: "https://www.linkedin.com/in/jamescodegaard/", twitter_handle: "@NASA", website_url: "https://www.firstmenonthemoon.com/", resume_url: "https://www.mint.com/", github_url: "https://www.github.com/jamescodegaard", photo_url: "https://www.uarti.com/wp-content/uploads/2017/08/fish-bowl-small-size.jpg"},
  {first_name: "Colin", last_name: "Klein", email: "colin@gmail.com", password: "password", phone_number: "881-088-8809", bio: "There once was a shark that could bark", linkedin_url: "https://www.linkedin.com/in/colintklein/", twitter_handle: "@colinkelin", website_url: "https://thefo.nz/", resume_url: "https://www.snopes.com/", github_url: "www.github.com/ct23", photo_url: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2016/09/29/15/hp.jpg?w968h681"},
  {first_name: "Moshe", last_name: "Segelman", email: "moshe@gmail.com", password: "password", phone_number: "484-444-8449", bio: "There once was a spider that wanted to fight her", linkedin_url: "https://www.linkedin.com/in/moshe-segelman/", twitter_handle: "@sportscenter", website_url: "https://chickswithstevebuscemeyes.tumblr.com/", resume_url: "https://lifehacker.com/", github_url: "https://www.github.com/moshesegelman", photo_url: "https://modernfarmer.com/wp-content/uploads/2017/12/Funny-Sheep-Facts-1200x800.jpg"},
  {first_name: "Sam", last_name: "Blank", email: "sam@gmail.com", password: "password", phone_number: "221-222-2222", bio: "There once was a goat in a boat", linkedin_url: "https://www.linkedin.com/in/sam-blank45/", twitter_handle: "@barstoolsports", website_url: "https://www.rainymood.com/", resume_url: "https://tastedive.com/", github_url: "https://www.github.com/samblank45", photo_url: "https://ichef.bbci.co.uk/news/410/cpsprodpb/D6B0/production/_95806945_gettyimages-590147780.jpg"},
  {first_name: "Ian", last_name: "Fletcher", email: "ian@gmail.com", password: "password", phone_number: "111-081-1726", bio: "There once was a cow named Bow-Wow", linkedin_url: "https://www.linkedin.com/in/ian-fletcher96/", twitter_handle: "@MarthaStewart", website_url: "http://www.instantwhoop.com/", resume_url: "https://asoftmurmur.com/", github_url: "https://www.github.com/ianfletcher55", photo_url: "https://vignette.wikia.nocookie.net/cultivation-chat-group/images/f/f4/Fire_Phoenix.jpg/revision/latest?cb=20180417032019"},
])
Education.create!([
  {start_date: "2011-08-25", end_date: "2015-05-11", degree: "computer science", university_name: "Carnegie Mellon University", details: "Student is an honor roll student who obtained an degree in computer science", student_id: 1},
  {start_date: "2014-08-27", end_date: "2018-05-17", degree: "history", university_name: "Brown University", details: "Student studied for 4 years at Brown University for a history degree along with a mathematics minor", student_id: 2}
])

Capstone.create([
  {name: "Funny Fish Database", description: "A collection of the funniest looking fish alive!", url: "www.funnyfish.com", screenshot_url: "https://www.bestfunnies.com/wp-content/uploads/2012/08/Funny-Fish-08.jpg", student_id: 1},
  {name: "Code Memes", description: "Input your issue and a code meme will be generated to match your mood.", url: "www.codememes.com", screenshot_url: "https://www.probytes.net/wp-content/uploads/2018/01/5-1.png", student_id: 2}, 
  {name: "Excuse Generator", description: "Generates excuses for when you are late for the zoom call.", url: "www.fastexcuse.com", screenshot_url: "https://i.chzbgr.com/full/9196762368/hC7176AFB/facial-expression-boss-youre-30-minutes-late-me-a-queen-is-never-late-everyone-else-is-simply-early", student_id: 3}
])